### ISSUE TITLE
Exception when sending DHCP discover packet

### ISSUE THREAD

**Issue by mdln1024** [kamorin/DHCPig#17]
On current Kali, it fails sending the DHCP discover packet.

```
root@kali:~# dhcpig eth0
[ -- ] [INFO] - using interface eth0
[DBG ] Thread 0 - (Sniffer) READY
[DBG ] Thread 1 - (Sender) READY
[--->] DHCP_Discover
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/bin/dhcpig", line 516, in run
    sendPacket(dhcp_discover)
  File "/usr/bin/dhcpig", line 413, in sendPacket
    sendp(pkt, iface=conf.iface)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 315, in sendp
    verbose=verbose, realtime=realtime, return_packets=return_packets)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 276, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 551, in send
    return SuperSocket.send(self, x)
  File "/usr/lib/python2.7/dist-packages/scapy/supersocket.py", line 42, in send
    sx = raw(x)
  File "/usr/lib/python2.7/dist-packages/scapy/compat.py", line 72, in raw
    return x.__bytes__()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 345, in __bytes__
    return self.build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 444, in build
    p = self.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 429, in do_build
    pay = self.do_build_payload()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 416, in do_build_payload
    return self.payload.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 429, in do_build
    pay = self.do_build_payload()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 416, in do_build_payload
    return self.payload.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 429, in do_build
    pay = self.do_build_payload()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 416, in do_build_payload
    return self.payload.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 429, in do_build
    pay = self.do_build_payload()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 416, in do_build_payload
    return self.payload.do_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 426, in do_build
    pkt = self.self_build()
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 407, in self_build
    p = f.addfield(self, p, val)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 521, in addfield
    return s + self.i2m(pkt, val)
  File "/usr/lib/python2.7/dist-packages/scapy/layers/dhcp.py", line 269, in i2m
    lval = [f.addfield(pkt,b"",f.any2i(pkt,val)) for val in lval]
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 841, in addfield
    s = self.field.addfield(pkt, s, v)
  File "/usr/lib/python2.7/dist-packages/scapy/fields.py", line 80, in addfield
    return s+struct.pack(self.fmt, self.i2m(pkt,val))
error: cannot convert argument to integer

[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ -- ] timeout waiting on dhcp packet count 1
[ ?? ] 		waiting for first DHCP Server response
[ -- ] timeout waiting on dhcp packet count 2
[ ?? ] 		waiting for first DHCP Server response
[ ?? ] 		waiting for first DHCP Server response
[ -- ] timeout waiting on dhcp packet count 3
[ ?? ] 		waiting for first DHCP Server response
[ -- ] timeout waiting on dhcp packet count 4
[ ?? ] 		waiting for first DHCP Server response
^C[ -- ]  -----  ABORT ...  -----
[DBG ] Waiting for Thread 0 to die ...
[DBG ] Waiting for Thread 1 to die ...
```

Scapy version: 2.4.0

**Comment by mdln1024** [comment]
Downgrading is not going to happen, that would break a lot of other tools.

**Comment by Str-Gen** [comment]
This issue still exists when using Python2 Scapy 2.4.2-1.
I've tried debugging, but the error happens in Scapy's library code and VSCode doesn't pick it up. @mdln1024 Have you been able to resolve the issue for Scapy 2.4.0?

**Comment by Str-Gen** [comment]
I have tested with version 2.3.3 and that works. My idea is an unexpected interaction between this function in Scapy 2.4.2-1
 def i2m(self, pkt, x):
        """Convert internal value to machine value"""
        if x is None:
            x = 0
        elif isinstance(x, str):
            return raw(x)
        return x
and its counterpart in Scapy 2.3.3
  def i2m(self, pkt, x):
        """Convert internal value to machine value"""
        if x is None:
            x = 0
        return x
