### ISSUE TITLE
no working

### ISSUE THREAD

**Issue by grasses** [kamorin/DHCPig#3]
something error.

sh-3.2# python dhcp.3.py -c -v3  -l -a -i -o eth0
Traceback (most recent call last):
  File "dhcp.3.py", line 86, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/site-packages/scapy/all.py", line 25, in <module>
    from route import *
  File "/usr/local/lib/python2.7/site-packages/scapy/route.py", line 162, in <module>
    conf.route=Route()
  File "/usr/local/lib/python2.7/site-packages/scapy/route.py", line 22, in __init__
    self.resync()
  File "/usr/local/lib/python2.7/site-packages/scapy/route.py", line 31, in resync
    self.routes = read_routes()
  File "/usr/local/lib/python2.7/site-packages/scapy/arch/unix.py", line 86, in read_routes
    ifaddr = scapy.arch.get_if_addr(netif)
  File "/usr/local/lib/python2.7/site-packages/scapy/arch/__init__.py", line 36, in get_if_addr
    return socket.inet_ntoa(get_if_raw_addr(iff))
  File "/usr/local/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 187, in get_if_raw_addr
    i = dnet.intf()
AttributeError: 'module' object has no attribute 'intf'

Test in Mac.

**Comment by kamorin** [comment]
see this issue: https://github.com/Homebrew/homebrew-python/issues/212 , should be functional on Mac after a reinstall
